// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYLGtlVHkv9_VXoYJ5nGm4lLdh2zP7x44',
    appId: '1:513724220768:web:c295680af11d94f4960a05',
    messagingSenderId: '513724220768',
    projectId: 'home-fitness-d9553',
    authDomain: 'home-fitness-d9553.firebaseapp.com',
    storageBucket: 'home-fitness-d9553.appspot.com',
    measurementId: 'G-4L7D579Q5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJeeb7wkxZCtLvG0OSvCPWbTgUmp28bFM',
    appId: '1:513724220768:android:aec6f205c6a1fd03960a05',
    messagingSenderId: '513724220768',
    projectId: 'home-fitness-d9553',
    storageBucket: 'home-fitness-d9553.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoXtZEwi5DXpOitTeQug6nUUcM6RvDykA',
    appId: '1:513724220768:ios:1dcf1ae90eba42ca960a05',
    messagingSenderId: '513724220768',
    projectId: 'home-fitness-d9553',
    storageBucket: 'home-fitness-d9553.appspot.com',
    iosClientId: '513724220768-c8bq4ftos7aq21ehmoo0nog69d71r48a.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
